[package]
name = "yaaocr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
dotenv = "0.15.0"
htmd = "0.5.0"
reqwest = { version = "0.12.25", features = ["blocking", "cookies"] }
scraper = "0.25.0"
